---
- name: Install microk8s
  community.general.snap:
    name:
      - microk8s
    classic: true

- name: check micrik8s status
  ansible.builtin.shell:
    cmd: microk8s status --format yaml
  register: microk8s_status_cmd

#- name: debug
#  debug:
#    var: microk8s_status_cmd

- name: debug
  debug:
    msg: "{{microk8s_status_cmd.stdout | from_yaml | keys}}"

#- name: enable microk8s metallb
#  ansible.builtin.shell:
#    cmd: microk8s enable metallb
#  register: microk8s_enable_metallb_cmd
#  when: "metallb" in microk8s_status_cmd.stdout
