---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: terraria-server
  annotations:
    metallb.universe.tf/address-pool: terraria-server-185
spec:
  selector:
    app.kubernetes.io/name: terraria
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: LoadBalancer
