---
- name: pulling repo for terraria
  ansible.builtin.shell:
    cmd: |
      microk8s helm3 repo \
        add \
          terraria \
          https://www.seppevolkaerts.be/terraria-helm-charts/
  changed_when: false

#- name: Render the file values.yaml
#  template:
#    src: values.yaml
#    dest: /home/vagrant/valheim-server/chart/values.yaml

- name: install helmchart
  ansible.builtin.shell:
    cmd: |
      microk8s helm3 upgrade \
        --install \
          "terraira1" \
          terraria/terraria
  changed_when: false

      microk8s kubectl apply -f /home/vagrant/terraria-server/metallb-config.yaml

- name: Render the file dansdogservice.conf
  template:
    src: metallb-config.yaml
    dest: /home/vagrant/tmp