---
- name: Terraria Playbook
  hosts: localhost
  become: true

  tasks:
    - name: Ensure the microk8s service is running
      include_role:
        name: microk8s

    - name: Ensure the terraria_microk8s service is running
      include_role:
        name: terraria_microk8s
